export const buildPretestSlice = (d) => ({
  preTestSection: d.preTestSection,
  setPreTestSection: d.setPreTestSection,
  preTestQuestions: d.preTestQuestions,
  setPreTestQuestions: d.setPreTestQuestions,
  preTestCurrentQuestion: d.preTestCurrentQuestion,
  setPreTestCurrentQuestion: d.setPreTestCurrentQuestion,
  preTestScore: d.preTestScore,
  setPreTestScore: d.setPreTestScore,
  preTestTimer: d.preTestTimer,
  setPreTestTimer: d.setPreTestTimer,
  preTestTimerActive: d.preTestTimerActive,
  setPreTestTimerActive: d.setPreTestTimerActive,
  preTestResults: d.preTestResults,
  setPreTestResults: d.setPreTestResults,
  completedSections: d.completedSections,
  showPreTestPopup: d.showPreTestPopup,
  isPretest: d.isPretest,
  isPretestIntroVisible: d.isPretestIntroVisible,
  setIsPretest: d.setIsPretest,
  pretestQuestionCount: d.pretestQuestionCount,
  pretestTimeLimitMs: d.pretestTimeLimitMs,
  pretestRemainingMs: d.pretestRemainingMs,
  pretestResult: d.pretestResult,
  setPretestResult: d.setPretestResult,
  setIsPretestIntroVisible: d.setIsPretestIntroVisible,
  stopPretestTimer: d.stopPretestTimer,
});
